[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#4c4f69"
bright_foreground = "#4c4f69"
[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"
[colors.search]
matches = { foreground = "#eff1f5", background = "#8c8fa1" }
focused_match = { foreground = "#eff1f5", background = "#40a02b" }
[colors.hints]
start = { foreground = "#eff1f5", background = "#df8e1d" }
end = { foreground = "#eff1f5", background = "#8c8fa1" }
[colors.selection]
text = "#eff1f5"
background = "#dc8a78"
[colors.normal]
black = "#5c5f77"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#acb0be"
[colors.bright]
black = "#6c6f85"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#bcc0cc"
[colors.dim]
black = "#5c5f77"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#acb0be"
