# overlays/theme-data/alacritty-latte.toml

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#4c4f69"
bright_foreground = "#4c4f69"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#7287fd"

[colors.search.matches]
foreground = "#eff1f5"
background = "#8839ef"

[colors.search.focused_match]
foreground = "#eff1f5"
background = "#40a02b"

[colors.footer_bar]
foreground = "#eff1f5"
background = "#9ca0b0"

[colors.hints.start]
foreground = "#eff1f5"
background = "#d20f39"

[colors.hints.end]
foreground = "#eff1f5"
background = "#9ca0b0"

[colors.selection]
text = "#eff1f5"
background = "#dc8a78"

[colors.normal]
black = "#4c4f69"
red = "#d20f39"
# Green: Custom darkened value
green = "#358523"
# Yellow: Custom darkened value
yellow = "#8F5E13"
blue = "#1e66f5"
magenta = "#8839ef"
cyan = "#04a5e5"
# White: Mapped to Dark Grey
white = "#5c5f77"

[colors.bright]
black = "#5c5f77"
red = "#d20f39"
green = "#358523"
yellow = "#8F5E13"
blue = "#1e66f5"
magenta = "#8839ef"
cyan = "#04a5e5"
white = "#5c5f77"

[colors.dim]
black = "#6c6f85"
red = "#d20f39"
green = "#40a02b"
yellow = "#8F5E13"
blue = "#1e66f5"
magenta = "#8839ef"
cyan = "#04a5e5"
white = "#5c5f77"
